import { writable } from 'svelte/store';

// 15 total
const boostDeck = writable([
  'chastity',
  'eradicate',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'chester',
  'gaze',
  'rejuvenate',
  'rejuvenate',
  'charge',
  'charge',
  'growth',
  'growth', 
  'feast',
  'feast',
  'cookieJar',
  'cookieJar',
  'oreoCookie',
  'chocoChipCookie',
  'thumbprintCookie',
  'oatmealCookie',
  'cookieCrumbs',
  'cookieCrumbs',
  'cookieCrumbs',
  'cookieCrumbs'
]);

export default boostDeck;