// @ts-ignore
import { writable } from 'svelte/store';

const cardDetails = writable({
  // Humans
  emperor: {
    title: 'emperor',
    displayTitle: 'Emperor',
    points: 10,
    amount: 1,
    rank: 'legendary',
    trait: 'Human points are doubled and all cards in your hand will count towards your final score, regardless of race.',
    traitTitle: 'No Discrimination',
    description: 'The leader of the human race.',
    race: 'human',
    image: '/humans/emperor.gif'
  },
  commander: {
    title: 'commander',
    displayTitle: 'Commander',
    points: 8,
    amount: 2,
    rank: 'epic',
    trait: 'When the commander is in your hand, all humans you have will receive +1 point, including commanders. This effect also stacks with the emperor.',
    traitTitle: 'Rally',
    description: 'Powerful warrior second only to the emperor.',
    race: 'human',
    image: '/humans/commander.png'
  },
  assassin: {
    title: 'assassin',
    displayTitle: 'Assassin',
    points: 6,
    amount: 3,
    rank: 'amazing',
    trait: '',
    traitTitle: '',
    description: 'A highly skilled professional killer.',
    race: 'human',
    image: '/humans/assassin.png'
  },
  knight: {
    title: 'knight',
    displayTitle: 'Knight',
    points: 4,
    amount: 4,
    rank: 'good',
    trait: '',
    traitTitle: '',
    description: 'A middle ranked warrior.',
    race: 'human',
    image: '/humans/knight.png'
  },
  soldier: {
    title: 'soldier',
    displayTitle: 'Soldier',
    points: 3,
    amount: 4,
    rank: 'good',
    trait: '',
    traitTitle: '',
    description: 'A low ranked warrior.',
    race: 'human',
    image: '/humans/soldier.png'
  },
  scout: {
    title: 'scout',
    displayTitle: 'Scout',
    points: 2 ,
    amount: 5,
    rank: 'basic',
    trait: '',
    traitTitle: '',
    description: 'The lowest ranked in the human army.',
    race: 'human',
    image: '/humans/scout.png'
  },
  villager: {
    title: 'villager',
    displayTitle: 'Villager',
    points: 1,
    amount: 6,
    rank: 'basic',
    trait: '',
    traitTitle: '',
    description: 'An innocent villager.',
    race: 'human',
    image: '/humans/villager.png'
  },

  // Goblins
  goblinLord: {
    title: 'goblinLord',
    displayTitle: 'Goblin Lord',
    points: 10,
    amount: 1,
    rank: 'legendary',
    trait: "If your hand contains only goblins, you receive an insane amount of bonus points. Beware, the elf king can block this trait, resulting in a draw.",
    traitTitle: 'Gobbledegook',
    description: 'The leader of the goblins.',
    race: 'goblin',
    image: '/goblins/goblin-lord.gif'
  },
  giant: {
    title: 'giant',
    displayTitle: 'Giant',
    points: 8,
    amount: 2,
    rank: 'epic',
    trait: '',
    traitTitle: '',
    description: 'The strongest weapons of the goblin lord.',
    race: 'goblin',
    image: '/goblins/giant.png'
  },
  troll: {
    title: 'troll',
    displayTitle: 'Troll',
    points: 6,
    amount: 3,
    rank: 'amazing',
    trait: '',
    traitTitle: '',
    description: 'Loyal high ranked soldier in the goblin army.',
    race: 'goblin',
    image: '/goblins/troll.png'
  },
  shaman: {
    title: 'shaman',
    displayTitle: 'Shaman',
    points: 5,
    amount: 4,
    rank: 'great',
    trait: '',
    traitTitle: '',
    description: 'A magic wielding goblin.',
    race: 'goblin',
    image: '/goblins/shaman.png'
  },
  thief: {
    title: 'thief',
    displayTitle: 'Thief',
    points: 3,
    amount: 4,
    rank: 'good',
    trait: '',
    traitTitle: '',
    description: 'A quick, elusive but weak goblin.',
    race: 'goblin',
    image: '/goblins/thief.png'
  },
  hobgoblin: {
    title: 'hobgoblin',
    displayTitle: 'Hobgoblin',
    points: 2,
    amount: 4,
    rank: 'good',
    trait: '',
    traitTitle: '',
    description: 'A low ranked goblin.',
    race: 'goblin',
    image: '/goblins/hobgoblin.png'
  },
  bokoblin: {
    title: 'bokoblin',
    displayTitle: 'Bokoblin',
    points: 1,
    amount: 6,
    rank: 'basic',
    trait: '',
    traitTitle: '',
    description: 'The weakest of goblins.',
    race: 'goblin',
    image: '/goblins/bokoblin.png'
  },

  // Elves
  elfKing: {
    title: 'elfKing',
    displayTitle: 'Elf King',
    points: 10,
    amount: 1,
    rank: 'legendary',
    trait: "If your hand contains only elves, they will have their points trippled! The elf king also prevents the enemy from using the goblin lord's special trait.",
    traitTitle: 'Superior Race',
    description: 'The purest, most powerful and respected leader of the elves.',
    race: 'elf',
    image: '/elves/elf-king.gif'
  },
  elfChampion: {
    title: 'elfChampion',
    displayTitle: 'Elf Champion',
    points: 8,
    amount: 2,
    rank: 'epic',
    trait: '',
    traitTitle: '',
    description: 'Elf king guard candidate.',
    race: 'elf',
    image: '/elves/champion.png'
  },
  darkElf: {
    title: 'darkElf',
    displayTitle: 'Dark Elf',
    points: 6,
    amount: 3,
    rank: 'amazing',
    trait: '',
    traitTitle: '',
    description: 'High ranked powerful elf.',
    race: 'elf',
    image: '/elves/dark-elf.png'
  },
  forestDweller: {
    title: 'forestDweller',
    displayTitle: 'Forest Dweller',
    points: 5,
    amount: 3,
    rank: 'amazing',
    trait: '',
    traitTitle: '',
    description: "An elf in tuned with nature, they're quite strong..",
    race: 'elf',
    image: '/elves/forest-dweller.png'
  },
  nadallen: {
    title: 'nadallen',
    displayTitle: 'Nadallen',
    points: 4,
    amount: 1,
    rank: 'great',
    trait: 'If both Nelladan and Nadallen are in your hand, they both receive +5 bonus points. This effect does not stack.',
    traitTitle: 'Twin Power',
    description: 'The stronger half of the rate elvan twins.',
    race: 'elf',
    image: '/elves/nadallen.png'
  },
  nelladan: {
    title: 'nelladan',
    displayTitle: 'Nelladan',
    points: 2,
    amount: 4,
    rank: 'good',
    trait: 'If both Nelladan and Nadallen are in your hand, they both receive +5 bonus points. This effect does not stack.',
    traitTitle: 'Twin Power',
    description: 'A rare elvan twin.',
    race: 'elf',
    image: '/elves/nelladan.png'
  },
  woodElf: {
    title: 'woodElf',
    displayTitle: 'Wood Elf',
    points: 3,
    amount: 4,
    rank: 'good',
    trait: '',
    traitTitle: '',
    description: 'An elf who aspires to be a forest dwelling elf.',
    race: 'elf',
    image: '/elves/wood-elf.png'
  },
  wildElf: {
    title: 'wildElf',
    displayTitle: 'Wild Elf',
    points: 2,
    amount: 4,
    rank: 'good',
    trait: '',
    traitTitle: '',
    description: 'An elf with no social status.',
    race: 'elf',
    image: '/elves/wild-elf.png'
  },
  bard: {
    title: 'bard',
    displayTitle: 'Bard',
    points: 1,
    amount: 4,
    rank: 'basic',
    trait: '',
    traitTitle: '',
    description: 'A weak musician.',
    race: 'elf',
    image: '/elves/bard.png'
  },

  // Dwarves
  longbeardLeader: {
    title: 'longbeardLeader',
    displayTitle: 'Longbeard Leader',
    points: 10,
    amount: 1,
    rank: 'legendary',
    trait: 'At the end of the game, if there are more discarded dwarves than remaining(or equal) dwarves in the deck, dwarves receive 50 bonus points. Additionally, the next card drawn will be a dwarf.',
    traitTitle: 'Last Man Standing',
    description: 'The bravest and most feared amongst the dwarves.',
    race: 'dwarf',
    image: '/dwarves/longbeard-leader.gif'
  },
  dwarfCommander:  {
    title: 'dwarfCommander',
    displayTitle: 'Dwarf Commander',
    points: 8,
    amount: 2,
    rank: 'epic',
    trait: '',
    traitTitle: '',
    description: 'Right hand man to the longbeard leader himself.',
    race: 'dwarf',
    image: '/dwarves/dwarf-commander.png'
  },
  alchemist: {
    title: 'alchemist',
    displayTitle: 'Alchemist',
    points: 6,
    amount: 2,
    rank: 'amazing',
    trait: '',
    traitTitle: '',
    description: 'A dwarven warrior wielding science as magic.',
    race: 'dwarf',
    image: '/dwarves/alchemist.png'
  },
  dwarfWarrior: {
    title: 'dwarfWarrior',
    displayTitle: 'Dwarf Warrior',
    points: 5,
    amount: 3,
    rank: 'amazing',
    trait: '',
    traitTitle: '',
    description: 'A strong and reliable dwarven warrior.',
    race: 'dwarf',
    image: '/dwarves/warrior.png'
  },
  hunter: {
    title: 'hunter',
    displayTitle: 'Hunter',
    points: 4,
    amount: 3,
    rank: 'great',
    trait: '',
    traitTitle: '',
    description: 'A strong and capable hunter.',
    race: 'dwarf',
    image: '/dwarves/hunter.png'
  },
  traveller: {
    title: 'traveller',
    displayTitle: 'Traveller',
    points: 3,
    amount: 4,
    rank: 'good',
    trait: '',
    traitTitle: '',
    description: 'An adventurous but feeble dwarf.',
    race: 'dwarf',
    image: '/dwarves/traveller.png'
  },
  miner: {
    title: 'miner',
    displayTitle: 'Miner',
    points: 2,
    amount: 3,
    rank: 'good',
    trait: '',
    traitTitle: '',
    description: 'An average miner, not great in a fight.',
    race: 'dwarf',
    image: '/dwarves/miner.png'
  },
  blacksmith: {
    title: 'blacksmith',
    displayTitle: 'Blacksmith',
    points: 2,
    amount: 3,
    rank: 'good',
    trait: '',
    traitTitle: '',
    description: 'A typical blacksmith, not very strong.',
    race: 'dwarf',
    image: '/dwarves/blacksmith.png'
  },
  bartender: {
    title: 'bartender',
    displayTitle: 'Bartender',
    points: 1,
    amount: 4,
    rank: 'basic',
    trait: '',
    traitTitle: '',
    description: 'A popular dwarf at the local pub, a serious drinker even amongst dwarves..',
    race: 'dwarf',
    image: '/dwarves/bartender.png'
  },
  hobbit: {
    title: 'hobbit',
    displayTitle: 'Hobbit',
    points: 1,
    amount: 4,
    rank: 'basic',
    trait: '',
    traitTitle: '',
    description: "Half dwarf, half human. Although rare and different, they're generally accepted by all dwarves.",
    race: 'dwarf',
    image: '/dwarves/hobbit.png'
  },

  // Bots
  crusher541A57: {
    title: 'crusher541A57',
    displayTitle: 'Crusher 541-A-57',
    points: 10,
    amount: 1,
    rank: 'legendary',
    trait: 'ALL bots will receive a +2 bons to their points. Additionally, Crusher will hack all bots and steal their points.',
    traitTitle: 'Binary Manipulator',
    description: 'The most advanced battle and hacking unit known to man.',
    race: 'bot',
    image: '/bots/crusher-5A1A-57.gif'
  },
  ai: {
    title: 'ai',
    displayTitle: 'A.I.',
    points: 8,
    amount: 2,
    rank: 'epic',
    trait: '',
    traitTitle: '',
    description: 'The core of the modern bot society.',
    race: 'bot',
    image: '/bots/ai.png'
  },
  faeBot: {
    title: 'faeBot',
    displayTitle: 'Fae Bot',
    points: 6,
    amount: 3,
    rank: 'amazing',
    trait: '',
    traitTitle: '',
    description: 'A bot created as a gift to the elves as a peace treaty.',
    race: 'bot',
    image: '/bots/fae-bot.png'
  },
  sawBot3000: {
    title: 'sawBot3000',
    displayTitle: 'Sawbot-3000',
    points: 4,
    amount: 4,
    rank: 'great',
    trait: '',
    traitTitle: '',
    description: 'A bot designed to kill, beware.',
    race: 'bot',
    image: '/bots/saw-bot-3000.png'
  },
  infernoBot: {
    title: 'infernoBot',
    displayTitle: 'Inferno Bot',
    points: 3,
    amount: 4,
    rank: 'great',
    trait: '',
    traitTitle: '',
    description: 'An angry aggressive bot, known to attack on sight.',
    race: 'bot',
    image: '/bots/inferno-bot.png'
  },
  incubator: {
    title: 'incubator',
    displayTitle: 'Incubator',
    points: 2,
    amount: 5,
    rank: 'good',
    trait: '',
    traitTitle: '',
    description: 'A weak mother bot used to raise young infants.',
    race: 'bot',
    image: '/bots/incubator.png'
  },
  virus: {
    title: 'virus',
    displayTitle: 'Virus',
    points: -2,
    amount: 7,
    rank: 'basic',
    trait: '',
    traitTitle: '',
    description: 'A common computer virus.',
    race: 'bot',
    image: '/bots/virus.png'
  },

  // Beasts
  dreamDestroyer: { 
    title: 'dreamDestroyer',
    displayTitle: 'Dream Destroyer',
    points: 10,
    amount: 1,
    rank: 'legendary',
    trait: 'All of your beasts are worth 10 points.',
    traitTitle: 'Roid Rage',
    description: 'The fiercest creature in the animal kingdom.',
    race: 'beast',
    image: '/beasts/dream-destroyer.gif'
  },
  rhino: {
    title: 'rhino',
    displayTitle: 'Rhinestone',
    points: 7,
    amount: 3,
    rank: 'amazing',
    trait: '',
    traitTitle: '',
    description: 'A feared beast at the top of the food chain.',
    race: 'beast',
    image: '/beasts/rhino.png'
  },
  bear: {
    title: 'bear',
    displayTitle: 'Theodore Thunderpaws',
    points: 7,
    amount: 3,
    rank: 'amazing',
    trait: '',
    traitTitle: '',
    description: 'A powerful top level beast, matched by few.',
    race: 'beast',
    image: '/beasts/bear.png'
  },
  lion: {
    title: 'lion',
    displayTitle: 'Savannah Goldenmane',
    points: 6,
    amount: 4,
    rank: 'great',
    trait: '',
    traitTitle: '',
    description: 'The original kings of the jungle.',
    race: 'beast',
    image: '/beasts/lion.png'
  },
  panther: {
    title: 'panther',
    displayTitle: 'Panthera Nocturna',
    points: 5,
    amount: 4,
    rank: 'great',
    trait: '',
    traitTitle: '',
    description: "A quick and efficient beast, known to stalk it's prey before pouncing.",
    race: 'beast',
    image: '/beasts/panther.png'
  },
  wolf: {
    title: 'wolf',
    displayTitle: 'Alpha Wolfbane',
    points: 4,
    amount: 4,
    rank: 'great',
    trait: '',
    traitTitle: '',
    description: 'A lone wolf with the strength of a pack.',
    race: 'beast',
    image: '/beasts/wolf.png'
  },
  fox: {
    title: 'fox',
    displayTitle: 'Finn Foxglove',
    points: 3,
    amount: 4,
    rank: 'good',
    trait: '',
    traitTitle: '',
    description: 'A fox on steroids.',
    race: 'beast',
    image: '/beasts/fox.png'
  },
  dog: {
    title: 'dog',
    displayTitle: 'Pawl Barkington',
    points: 2,
    amount: 4,
    rank: 'good',
    trait: '',
    traitTitle: '',
    description: 'More bark than bite, recognized as the weakest beast.',
    race: 'beast',
    image: '/beasts/dog.png'
  }
});

export default cardDetails;