import { writable } from 'svelte/store';

/*
 * Legendary = leader
 * Epic = Great ability, usually 2nd in command
 * Amazing = special trait e.g. 2 races or elf twins
 * Great = No trait but high stat (6 or more)
 * Poor = No trait and points 5 or less.
 */
const cardDetails = writable({
  // Humans
  emperor: {
    title: 'emperor',
    displayTitle: 'Emperor',
    points: 10,
    amount: 1,
    rarity: 'legendary',
    traitTitle: 'Unity Pact',
    trait: "Human points are doubled and all races in your hand except xenos will count towards your final score.",
    description: 'The leader of the human race.',
    race: 'human',
    otherRaces: [],
    image: '/humans/emperor.png'
  },
  commander: {
    title: 'commander',
    displayTitle: 'Commander',
    points: 7,
    amount: 2,
    rarity: 'epic',
    traitTitle: 'Rally',
    trait: 'When the commander is in your hand, all humans you have will receive +1 point, including commanders. This effect also stacks with the emperor.',
    description: 'Powerful soldier second only to the emperor.',
    race: 'human',
    otherRaces: [],
    image: '/humans/commander.png'
  },
  lupin: {
    title: 'lupin',
    displayTitle: 'Lupin',
    points: 8,
    amount: 2,
    rarity: 'amazing',
    traitTitle: 'Full Moon',
    trait: 'Lupin counts as both human and beast/wolf.',
    description: 'A human who was bit by a strange wolf and now transforms on full moons.',
    race: 'human',
    otherRaces: ['beast'],
    image: '/humans/werewolf.png'
  },
  assassin: {
    title: 'assassin',
    displayTitle: 'Assassin',
    points: 5,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'A highly skilled professional killer.',
    race: 'human',
    otherRaces: [],
    image: '/humans/assassin.png'
  },
  knight: {
    title: 'knight',
    displayTitle: 'Knight',
    points: 4,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'A middle ranked soldier.',
    race: 'human',
    otherRaces: [],
    image: '/humans/knight.png'
  },
  soldier: {
    title: 'soldier',
    displayTitle: 'Soldier',
    points: 3,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'A low ranked soldier.',
    race: 'human',
    otherRaces: [],
    image: '/humans/soldier.png'
  },
  scout: {
    title: 'scout',
    displayTitle: 'Scout',
    points: 2,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'The lowest ranked in the human army.',
    race: 'human',
    otherRaces: [],
    image: '/humans/scout.png'
  },
  villager: {
    title: 'villager',
    displayTitle: 'Villager',
    points: 1,
    amount: 2,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'An innocent villager.',
    race: 'human',
    otherRaces: [],
    image: '/humans/villager.png'
  },
  villager2: {
    title: 'villager2',
    displayTitle: 'Villager',
    points: 1,
    amount: 2,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'An innocent villager.',
    race: 'human',
    otherRaces: [],
    image: '/humans/villager2.png'
  },

  // Goblins
  goblinLord: {
    title: 'goblinLord',
    displayTitle: 'Goblin Lord',
    points: 20,
    amount: 1,
    rarity: 'legendary',
    traitTitle: 'Gobbledegook',
    trait: "If your hand contains only goblins, you receive an insane amount of bonus points, doesn't count goblin lord's mark. Beware, the elf king can block this trait, resulting in a draw.",
    description: 'The leader of the goblins.',
    race: 'goblin',
    otherRaces: [],
    image: '/goblins/goblin-lord.gif'
  },
  warchief: {
    title: 'warchief',
    displayTitle: 'Warchief',
    points: 10,
    amount: 1,
    rarity: 'epic',
    traitTitle: "Chieftain's call",
    trait: "When drawn the next card drawn will be the goblin lord's mark, if it's still in the deck. Does not trigger if this card is in starting hand.",
    description: 'Born in battle, this brutal war hungry goblin is second only to the goblin lord himself.',
    race: 'goblin',
    otherRaces: [],
    image: '/goblins/warchief.png'
  },
  goblinLordsMark: {
    title: 'goblinLordsMark',
    displayTitle: "Goblin Lord's Mark",
    points: 0,
    amount: 1,
    rarity: 'epic',
    traitTitle: "Death's Mark",
    trait: 'When drawn, draw the goblin lord next turn. If no goblin lord, draw a goblin. If no goblin, draw a random card.',
    description: 'A sign that the goblin lord is near.',
    race: 'goblin-ish',
    otherRaces: [],
    image: '/goblins/goblin-lord_mark.png'
  },
  troll: {
    title: 'troll',
    displayTitle: 'Troll',
    points: 8,
    amount: 3,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'Loyal high ranked soldier in the goblin army.',
    race: 'goblin',
    otherRaces: [],
    image: '/goblins/troll.png'
  },
  shaman: {
    title: 'shaman',
    displayTitle: 'Shaman',
    points: 7,
    amount: 3,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'A magic wielding goblin.',
    race: 'goblin',
    otherRaces: [],
    image: '/goblins/shaman.png'
  },
  thief: {
    title: 'thief',
    displayTitle: 'Thief',
    points: 5,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'A quick, elusive but weak goblin.',
    race: 'goblin',
    otherRaces: [],
    image: '/goblins/thief.png'
  },
  hobgoblin: {
    title: 'hobgoblin',
    displayTitle: 'Hobgoblin',
    points: 4,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'A low ranked goblin.',
    race: 'goblin',
    otherRaces: [],
    image: '/goblins/hobgoblin.png'
  },
  bokoblin: {
    title: 'bokoblin',
    displayTitle: 'Bokoblin',
    points: 2,
    amount: 4,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'The weakest of goblins.',
    race: 'goblin',
    otherRaces: [],
    image: '/goblins/bokoblin.png'
  },

  // Elves
  elfKing: {
    title: 'elfKing',
    displayTitle: 'Elf King',
    points: 15,
    amount: 1,
    rarity: 'legendary',
    traitTitle: 'Superior Race',
    trait: "If your hand contains only elves, they will have their points trippled, otherwise doubled! The elf king also prevents the enemy from using the goblin lord's special trait.",
    description: 'The purest, most powerful and respected leader of the elves.',
    race: 'elf',
    otherRaces: [],
    image: '/elves/elf_king.png'
  },
  elfChampion: {
    title: 'elfChampion',
    displayTitle: 'Elf Champion',
    points: 12,
    amount: 1,
    rarity: 'amazing',
    traitTitle: 'Stand Guard',
    trait: 'The elf champion is always the first elf drawn.',
    description: 'Destined to be the next elf king, this elf champion lost an arm in battle and came back even more fierce.',
    race: 'elf',
    otherRaces: [],
    image: '/elves/elf_champion.png'
  },
  nadallen: {
    title: 'nadallen',
    displayTitle: 'Nadallen',
    points: 5,
    amount: 1,
    rarity: 'amazing',
    traitTitle: 'Twin Power',
    trait: 'If both Nelladan and Nadallen are in your hand, they both receive +5 bonus points. This effect stacks with each extra Nelladan and the elf king.',
    description: 'The stronger half of the rare elvan twins.',
    race: 'elf',
    otherRaces: [],
    image: '/elves/nadallen.png'
  },
  highElf: {
    title: 'highElf',
    displayTitle: 'High Elf',
    points: 10,
    amount: 3,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: "An elf in tune with nature, they're quite strong..",
    race: 'elf',
    otherRaces: [],
    image: '/elves/high_elf.png'
  },
  darkElf: {
    title: 'darkElf',
    displayTitle: 'Dark Elf',
    points: 9,
    amount: 3,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'High ranked powerful elf.',
    race: 'elf',
    otherRaces: [],
    image: '/elves/dark_elf.png'
  },
  nelladan: {
    title: 'nelladan',
    displayTitle: 'Nelladan',
    points: 2,
    amount: 4,
    rarity: 'great',
    traitTitle: 'Twin Power',
    trait: 'If both Nelladan and Nadallen are in your hand, they both receive +5 bonus points. This effect stacks with the elf king.',
    description: 'A rare elvan twin.',
    race: 'elf',
    otherRaces: [],
    image: '/elves/nelladan.png'
  },
  woodElf: {
    title: 'woodElf',
    displayTitle: 'Wood Elf',
    points: 6,
    amount: 3,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'An elf who aspires to be a forest dwelling elf.',
    race: 'elf',
    otherRaces: [],
    image: '/elves/wood_elf.png'
  },
  forestDweller: {
    title: 'forestDweller',
    displayTitle: 'Wild Elf',
    points: 4,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'An elf with no social status.',
    race: 'elf',
    otherRaces: [],
    image: '/elves/forest_dweller.png'
  },
  bard: {
    title: 'bard',
    displayTitle: 'Bard',
    points: 2,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'A weak musician.',
    race: 'elf',
    otherRaces: [],
    image: '/elves/bard.png'
  },

  // Dwarves
  longbeardLeader: {
    title: 'longbeardLeader',
    displayTitle: 'Longbeard Leader',
    points: 12,
    amount: 1,
    rarity: 'legendary',
    traitTitle: 'Drunken revenge',
    trait: 'Gain 5+ points for every discarded dwarf. Additionally, if you drew this card the next card you draw will be a dwarf if one is available.',
    description: 'The bravest and most feared amongst the dwarves.',
    race: 'dwarf',
    otherRaces: [],
    image: '/dwarves/longbeard-leader.png'
  },
  dwarfCommander:  {
    title: 'dwarfCommander',
    displayTitle: 'Dwarf Commander',
    points: 10,
    amount: 2,
    rarity: 'epic',
    traitTitle: 'Recruit',
    trait: 'When drawn the next card you draw will be a dwarf. Has no effect if in starting hand or if no dwarves remain.',
    description: 'Right hand man to the longbeard leader himself.',
    race: 'dwarf',
    otherRaces: [],
    image: '/dwarves/commander.png'
  },
  alchemist: {
    title: 'alchemist',
    displayTitle: 'Alchemist',
    points: 8,
    amount: 2,
    rarity: 'amazing',
    traitTitle: 'Another Round',
    trait: 'When discarded get a 50% chance to draw a dwarf next turn, does not stack. Must be dwarves remaining in deck.',
    description: 'A dwarven warrior wielding science as magic.',
    race: 'dwarf',
    otherRaces: [],
    image: '/dwarves/alchemist.png'
  },
  dwarfWarrior: {
    title: 'dwarfWarrior',
    displayTitle: 'Dwarf Warrior',
    points: 6,
    amount: 3,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'A strong and reliable dwarven warrior.',
    race: 'dwarf',
    otherRaces: [],
    image: '/dwarves/warrior.png'
  },
  hunter: {
    title: 'hunter',
    displayTitle: 'Hunter',
    points: 5,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'A strong and capable hunter.',
    race: 'dwarf',
    otherRaces: [],
    image: '/dwarves/hunter.png'
  },
  traveller: {
    title: 'traveller',
    displayTitle: 'Traveller',
    points: 4,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'An adventurous but feeble dwarf.',
    race: 'dwarf',
    otherRaces: [],
    image: '/dwarves/traveller.png'
  },
  miner: {
    title: 'miner',
    displayTitle: 'Miner',
    points: 3,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'An average miner, not great in a fight.',
    race: 'dwarf',
    otherRaces: [],
    image: '/dwarves/miner.png'
  },
  blacksmith: {
    title: 'blacksmith',
    displayTitle: 'Blacksmith',
    points: 3,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'A typical blacksmith, not very strong.',
    race: 'dwarf',
    otherRaces: [],
    image: '/dwarves/blacksmith.png'
  },
  bartender: {
    title: 'bartender',
    displayTitle: 'Bartender',
    points: 1,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'A popular dwarf at the local pub, a serious drinker even amongst dwarves..',
    race: 'dwarf',
    otherRaces: [],
    image: '/dwarves/bartender.png'
  },
  hobbit: {
    title: 'hobbit',
    displayTitle: 'Hobbit',
    points: 2,
    amount: 2,
    rarity: 'poor',
    traitTitle: 'Half and half',
    trait: 'Hobbit points count towards both dwarves and humans.',
    description: "Half dwarf, half human. Although rare and different, they're generally accepted by all dwarves.",
    race: 'dwarf',
    otherRaces: ['human'],
    image: '/dwarves/hobbit.png'
  },


  // Bots
  ai: {
    title: 'ai',
    displayTitle: 'A.I.',
    points: 11,
    amount: 1,
    rarity: 'legendary',
    traitTitle: 'Binary Manipulator',
    trait: 'ALL bots will receive +2 points, effectively quarantining viruses. Additionally, A.I. will hack all bots and steal their points.',
    description: 'The core of the modern bot society, excels in probability computation and hacking.',
    race: 'bot',
    otherRaces: [],
    image: '/bots/ai.png'
  },
  protectron: {
    title: 'protectron',
    displayTitle: 'Protectron',
    points: 9,
    amount: 2,
    rarity: 'epic',
    traitTitle: 'Antivirus',
    trait: 'Reprograms viruses into helpful programs, increasing their point value by 8. Protectron will also receive +1 point for every reprogrammed virus.',
    description: 'The most advanced battle bot and previous leader of the bots until A.I. took over, now second in command.',
    race: 'bot',
    otherRaces: [],
    image: '/bots/protectron.png'
  },
  faeBot: {
    title: 'faeBot',
    displayTitle: 'Fae Bot',
    points: 8,
    amount: 2,
    rarity: 'amazing',
    traitTitle: 'Fae Loader',
    trait: 'Fae Bot counts as both bot and elf.',
    description: 'Created as a gift to the elves as a peace treaty.',
    race: 'bot',
    otherRaces: ['elf'],
    image: '/bots/fae-bot.png'
  },
  cyborg: {
    title: 'cyborg',
    displayTitle: 'Cyborg',
    points: 8,
    amount: 2,
    rarity: 'amazing',
    traitTitle: 'Human Loader',
    trait: 'Cyborg counts as both bot and human.',
    description: 'A human who underwent experiments to become mostly machine.',
    race: 'bot',
    otherRaces: ['human'],
    image: '/bots/cyborg.png'
  },
    sawBot: {
    title: 'sawBot',
    displayTitle: 'Sawbot-3000',
    points: 7,
    amount: 3,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'A bot designed to kill humans and trees, but mostly humans, beware.',
    race: 'bot',
    otherRaces: [],
    image: '/bots/saw-bot.png'
  },
  killBot: {
    title: 'killBot',
    displayTitle: 'Kill Bot',
    points: 6,
    amount: 3,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'An aggressive bot, known to attack on sight.',
    race: 'bot',
    otherRaces: [],
    image: '/bots/kill-bot.png'
  },
  incuBot: {
    title: 'incuBot',
    displayTitle: 'Incu Bot',
    points: 5,
    amount: 3,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'A weak incubator bot used to repair small bots.',
    race: 'bot',
    otherRaces: [],
    image: '/bots/incu-bot.png'
  },
  virus: {
    title: 'virus',
    displayTitle: 'Virus',
    points: -2,
    amount: 6,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'A common computer virus, can be reprogrammed by protectron or quarantined A.I.',
    race: 'bot',
    otherRaces: [],
    image: '/bots/virus.png'
  },

  // Beasts
  dreamDestroyer: {
    title: 'dreamDestroyer',
    displayTitle: 'Dream Destroyer',
    points: 14,
    amount: 1,
    rarity: 'legendary',
    traitTitle: 'Dream Pact💤',
    trait: 'All of your beasts are worth 14 points.',
    description: 'The fiercest creature in all of the animal kingdom.',
    race: 'beast',
    otherRaces: [],
    image: '/beasts/dream-destroyer.png'
  },
  rhino: {
    title: 'rhino',
    displayTitle: 'Rhinestone',
    points: 10,
    amount: 1,
    rarity: 'epic',
    traitTitle: 'Thick skin',
    trait: 'If this card is in the player\'s hand at the end of the game, they will block all trap cards.',
    description: 'A feared beast at the top of the food chain.',
    race: 'beast',
    otherRaces: [],
    image: '/beasts/rhino.png'
  },
  wolf: {
    title: 'wolf',
    displayTitle: 'Alpha Wolfbane',
    points: 6,
    amount: 4,
    rarity: 'amazing',
    traitTitle: 'Wolf pack',
    trait: 'Receive +2 points for every wolf in your hand, including this one and werewolves.',
    description: 'A lone wolf with the strength of a pack.',
    race: 'beast',
    otherRaces: [],
    image: '/beasts/wolf.png'
  },
  dog: {
    title: 'dog',
    displayTitle: 'Pawl Barkington',
    points: 4,
    amount: 2,
    rarity: 'amazing',
    traitTitle: "Man's best friend",
    trait: 'If ally hand contains humans (or hobbit), pawl receives + 10 points at the end of the game.',
    description: 'More bark than bite, recognized as the weakest beast since he obeys humans.',
    race: 'beast',
    otherRaces: [],
    image: '/beasts/dog.png'
  },
  bear: {
    title: 'bear',
    displayTitle: 'Theo Thunderpaw',
    points: 9,
    amount: 2,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'A powerful top level beast, matched by few.',
    race: 'beast',
    otherRaces: [],
    image: '/beasts/bear.png'
  },
  lion: {
    title: 'lion',
    displayTitle: 'Goldenmane',
    points: 8,
    amount: 3,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'The original kings of the jungle.',
    race: 'beast',
    otherRaces: [],
    image: '/beasts/lion.png'
  },
  panther: {
    title: 'panther',
    displayTitle: 'Panth Nocturna',
    points: 7,
    amount: 3,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: "A quick and efficient beast, known to stalk it's prey before pouncing.",
    race: 'beast',
    otherRaces: [],
    image: '/beasts/panther.png'
  },
  fox: {
    title: 'fox',
    displayTitle: 'Finn Foxglove',
    points: 5,
    amount: 2,
    rarity: 'poor',
    traitTitle: '',
    trait: '',
    description: 'A fox on steroids.',
    race: 'beast',
    otherRaces: [],
    image: '/beasts/fox.png'
  },
  // Giraffes
  nightTerror: {
    title: 'nightTerror',
    displayTitle: 'Night Terror',
    points: 12,
    amount: 1,
    rarity: 'legendary',
    traitTitle: 'Nightmare Pact💤',
    trait: 'All of your beasts are worth 12 points.',
    description: 'Dream Destroyer\'s mother.',
    race: 'beast',
    otherRaces: [],
    image: '/beasts/night_terror.png'
  },
  elderGiraffe: {
    title: 'elderGiraffe',
    displayTitle: 'Granffey',
    points: 10,
    amount: 1,
    rarity: 'epic',
    traitTitle: 'Unicorn Pact🦄',
    trait: "Summons a very powerful ally.",
    description: 'This defender giraffe has gained the respect and trust of the royal family. Other beasts treat him as an extension of royalty.',
    race: 'beast',
    otherRaces: [],
    image: '/beasts/elder_giraffe.png'
  },
  adultGiraffe: {
    title: 'adultGiraffe',
    displayTitle: 'Giraffey',
    points: 6,
    amount: 1,
    rarity: 'amazing',
    traitTitle: 'Age',
    trait: "Ages into a more powerful card. Blocks card draw and discards while aging.",
    description: 'This giraffe is a loyal personal guard of the royal family.',
    race: 'beast',
    otherRaces: [],
    image: '/beasts/adult_giraffe.png'
  },
  kidGiraffe: {
    title: 'kidGiraffe',
    displayTitle: 'Calfy',
    points: 1,
    amount: 1,
    rarity: 'great',
    traitTitle: 'Grow',
    trait: "Grows into a more powerful card. Blocks card draw and discards while growing.",
    description: 'This calf is destined for greatness.',
    race: 'beast',
    otherRaces: [],
    image: '/beasts/kid_giraffe.png'
  },
  eggGiraffe: {
    title: 'eggGiraffe',
    displayTitle: '🦒Egg🦒',
    points: 0,
    amount: 1,
    rarity: 'poor',
    traitTitle: 'Hatch',
    trait: "Hatches into a more powerful card. Blocks card draw and discards while growing.",
    description: 'This egg is destined for greatness.',
    race: 'beast',
    otherRaces: [],
    image: '/beasts/egg_giraffe.png'
  },

  // Xenos (Alien hive colony)
  xenoGuard: {
    title: 'xenoGuard',
    displayTitle: 'Xeno Guard',
    points: 15,
    amount: 3,
    rarity: 'amazing',
    traitTitle: 'Antibodies',
    trait: 'If this card is in the player\'s hand at the end of the game, they will not receive any boosts.',
    description: 'The xenoGuard is a highly intelligent and powerful creature, feared by many. It is the most feared creature in the xeno hive, tasked with the safety of the xeno overlord.',
    race: 'xeno',
    otherRaces: [],
    image: '/xenos/xeno_guard.png'
  },
  warpstalker: {
    title: 'warpstalker',
    displayTitle: 'Warpstalker',
    points: 10, // random between 10-20
    amount: 3,
    rarity: 'amazing',
    traitTitle: 'Hive Resonance',
    trait: 'When drawn Warpstalker receives a random point value between 10 and 20 (inclusive), then applied to ALL warpstalkers in hand.',
    description: 'A xeno capable of riftwalking, similar to teleporting over short distances. Sometimes riftwalks to the wrong place.',
    race: 'xeno',
    otherRaces: [],
    image: '/xenos/warpstalker.png'
  },
  voidRunner: {
    title: 'voidRunner',
    displayTitle: 'Void Runner',
    points: 0, // increases by 1 per turn passed
    amount: 3,
    rarity: 'amazing',
    traitTitle: 'Hive Unity',
    trait: "When drawn the point value of all Void Runners in hand will be equal to the current turn.",
    description: "A non sentient xeno who's only purpose is to run and grow stronger. If it ever stops it will die.",
    race: 'xeno',
    otherRaces: [],
    image: '/xenos/void_runner.png'
  },
  nebulite: {
    title: 'nebulite',
    displayTitle: 'Nebulite',
    points: 0,
    amount: 3,
    rarity: 'amazing',
    traitTitle: 'Hive Blossom',
    trait: 'Buffs all xenos by +5, does not apply to self and does not stack with other Nebulites.',
    description: 'Artificially created xenos incapable of speech.',
    race: 'xeno',
    otherRaces: [],
    image: '/xenos/nebulite.png'
  },
  abyssolarian: {
    title: 'abyssolarian',
    displayTitle: 'Abyssolarian',
    points: 10,
    amount: 4,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'A feral xeno born in the darkest depths of Xenopp. Produces light to lure prey.',
    race: 'xeno',
    otherRaces: [],
    image: '/xenos/abyssolarian.png'
  },
  celenial: {
    title: 'celenial',
    displayTitle: 'Celenial',
    points: 8,
    amount: 4,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'The lowest of the xenos, often mistreated. Excluding the nebulites, celenials are the weakest of the xenos, often used as bait for the abyssolarians.',
    race: 'xeno',
    otherRaces: [],
    image: '/xenos/xeno_placeholder.png'
  },

  // Spirits
  spiritKing: {
    title: 'spiritKing',
    displayTitle: 'Spirit King',
    points: 25,
    amount: 1,
    rarity: 'legendary',
    traitTitle: 'Seance',
    trait: 'Reveals both player\'s hands while this is in your hand.',
    description: 'A powerful ancient spirit who represents life and death.',
    race: 'spirit',
    otherRaces: [],
    image: '/spirits/spirit_king.png'
  },
  darkSpirit: {
    title: 'darkSpirit',
    displayTitle: 'Darqnos',
    points: 15,
    amount: 1,
    rarity: 'epic',
    traitTitle: 'Enshrouded',
    trait: 'Prevents any of your cards from being exposed in any way (protects Brite and Spirit king).',
    description: 'A spirit born from all things impure.',
    race: 'spirit',
    otherRaces: [],
    image: '/spirits/dark_spirit.png'
  },
  lightSpirit: {
    title: 'lightSpirit',
    displayTitle: 'Brite',
    points: 20,
    amount: 1,
    rarity: 'amazing',
    traitTitle: 'Reveal',
    trait: 'This card is always exposed to the other player.',
    description: 'A spirit born from all things pure.',
    race: 'spirit',
    otherRaces: [],
    image: '/spirits/light_spirit.png'
  },
  earthSpirit: {
    title: 'earthSpirit',
    displayTitle: 'Pangee',
    points: 10,
    amount: 1,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'The spiritual embodiment of nature.',
    race: 'spirit',
    otherRaces: [],
    image: '/spirits/earth_spirit.png'
  },
  waterSpirit: {
    title: 'waterSpirit',
    displayTitle: 'Aqueous',
    points: 10,
    amount: 1,
    rarity: 'great',
    traitTitle: '',
    trait: '', // TODO: ability amkes u draw a blue jinn next
    description: 'The spiritual embodiment of the ocean and rain.',
    race: 'spirit',
    otherRaces: [],
    image: '/spirits/water_spirit.png'
  },
  iceSpirit: {
    title: 'iceSpirit',
    displayTitle: 'Glacos',
    points: 10,
    amount: 1,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'The spiritual embodiment of all things lacking energy.',
    race: 'spirit',
    otherRaces: [],
    image: '/spirits/ice_spirit.png'
  },
  fireSpirit: {
    title: 'fireSpirit',
    displayTitle: 'Ifrit',
    points: 10,
    amount: 1,
    rarity: 'great',
    traitTitle: '',
    trait: '', // TODO: Ability makes u draw a red jinn next
    description: 'The spiritual embodiment of fire and life.',
    race: 'spirit',
    otherRaces: [],
    image: '/spirits/fire_spirit.png'
  },
  lightningSpirit: {
    title: 'lightningSpirit',
    displayTitle: 'Lighthor',
    points: 10,
    amount: 1,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'The spiritual embodiment of energy and electricity.',
    race: 'spirit',
    otherRaces: [],
    image: '/spirits/lightning_spirit.png'
  },
  windSpirit: {
    title: 'windSpirit',
    displayTitle: 'Tailwos',
    points: 10,
    amount: 1,
    rarity: 'great',
    traitTitle: '',
    trait: '',
    description: 'The spiritual embodiment of wind and the weather.',
    race: 'spirit',
    otherRaces: [],
    image: '/spirits/wind_spirit.png'
  },
    blueSpirit: {
    title: 'blueSpirit',
    displayTitle: 'Bluejinn',
    points: 0,
    amount: 10,
    rarity: 'great',
    traitTitle: 'Blue Cluster',
    trait: 'If player holds 5 Bluejinns, they receive +200 spirit points (must be in hand, cannot discard).',
    description: 'A small blue spirit, thousands are manifested from woeful energy every day.',
    race: 'spirit',
    otherRaces: [],
    image: '/spirits/blue_spirit.png'
  },
  redSpirit: {
    title: 'redSpirit',
    displayTitle: 'Redjinn',
    points: 0,
    amount: 15,
    rarity: 'great',
    traitTitle: 'Red Cluster',
    trait: 'If player holds 5 Redjinns, they receive +100 spirit points (must be in hand, cannot discard).',
    description: 'A small red spirit, millions are manifested from hostile energy every day.',
    race: 'spirit',
    otherRaces: [],
    image: '/spirits/red_spirit.png'
  },

  // Boosts Cards:
  chastity: {
    title: 'chastity',
    displayTitle: 'Chastity',
    points: 0,
    amount: 1,
    rarity: 'legendary',
    traitTitle: 'Purity',
    trait: 'Gain chastity immediately, remains even if discarded. Blocks all trap cards except Corruption. If acquired by switcharoo, only active while in hand. Wipes infect, can be neutralized.',
    description: 'An intriguing artifact said to repel all evil.',
    race: 'boost',
    otherRaces: [],
    image: '/boosts/rainbow_boost.png'
  },
  eradicate: {
    title: 'eradicate',
    displayTitle: 'Eradicate',
    points: 0,
    amount: 1,
    rarity: 'epic',
    traitTitle: 'Eradication',
    trait: 'Cannot be blocked, when discarded removes all remaining trap cards from the deck.',
    description: 'This sentient volatile sprite is usually docile but can become eradic if provoked.',
    race: 'boost',
    otherRaces: [],
    image: '/boosts/eradicate.png'
  },
  chester: {
    title: 'chester',
    displayTitle: 'Chester',
    points: 0,
    amount: 1,
    rarity: 'epic',
    traitTitle: 'Bountiful Booty',
    trait: 'Discarding this card will instead transform it into a random legendary (race not boost/trap/neutral) if any are available. Cannot be found if player boosts are blocked.',
    description: 'A benevolent chest spirit that was born from the manifestation of peoples\' desires for riches.',
    race: 'boost',
    otherRaces: [],
    image: '/boosts/chester.png'
  },
  gaze: {
    title: 'Gaze',
    displayTitle: 'Gaze',
    points: 0,
    amount: 1,
    rarity: 'amazing',
    traitTitle: 'Prediction',
    trait: 'While in hand, grants player the ability to click on it to reveal remaining cards in deck. This can be blocked.',
    description: 'This being exists outside of time and reality, always watching but never interfering.',
    race: 'boost',
    otherRaces: [],
    image: '/boosts/gaze.png'
  },
  rejuvenate: {
    title: 'rejuvenate',
    displayTitle: 'Rejuvenate',
    points: 0,
    amount: 2,
    rarity: 'amazing',
    traitTitle: 'Rejuvenation',
    trait: 'When drawn player gains +10 points at the end of the game even after this card is discarded.',
    description: 'An artifact that is believed to strengthen all being.',
    race: 'boost',
    otherRaces: [],
    image: '/boosts/blue_boost.png'
  },
  cookieJar: {
    title: 'cookieJar',
    displayTitle: 'Cookie Jar',
    points: 0,
    amount: 3,
    rarity: 'amazing',
    traitTitle: 'No Cookie For You',
    trait: 'Grants +50 points to all races while in hand if your hand contains only bonus cards (boost, trap, neutral). This stacks with other cookie jars and can be blocked.',
    description: 'This notorius cookie jar gained sentience after being desecrated repeatedly. It vows to figure out once and for all who stole the cookie from the cookie jar.',
    race: 'boost',
    otherRaces: [],
    image: '/boosts/cookie_jar.png'
  },
  charge: {
    title: 'charge',
    displayTitle: 'Charge',
    points: 0,
    amount: 2,
    rarity: 'great',
    traitTitle: 'Recharge',
    trait: 'When drawn player gains +1 bot & human point each turn (stacks) at the end of the game even after this card is discarded.',
    description: 'This curious electrified liquid seems to only benefit electronics and the human anatomy.',
    race: 'boost',
    otherRaces: [],
    image: '/boosts/charge.png'
  },
  growth: {
    title: 'growth',
    displayTitle: 'Growth',
    points: 0,
    amount: 2,
    rarity: 'great',
    traitTitle: 'Stimulate',
    trait: 'When drawn player gains +1 goblin, elf & dwarf point each turn (stacks) at the end of the game even after this card is discarded.',
    description: 'This curious furry creature seems to promote growth in certain creatues.',
    race: 'boost',
    otherRaces: [],
    image: '/boosts/growth.png'
  },
  feast: {
    title: 'feast',
    displayTitle: 'Feast',
    points: 0,
    amount: 2,
    rarity: 'great',
    traitTitle: 'Feasting',
    trait: 'When drawn player gains +10 beast points at the end of the game even after this card is discarded.',
    description: 'An small furry creature with a large appetite.',
    race: 'boost',
    otherRaces: [],
    image: '/boosts/feast.png'
  },

  // Trap Cards
  corruption: {
    title: 'corruption',
    displayTitle: 'Corruption',
    points: 0,
    amount: 1,
    rarity: 'legendary',
    traitTitle: 'Impurity',
    trait: 'Gain courruption immediately, remains even if discarded. Blocks all boost cards except Chastity. If acquired by switcharoo, only active while in hand. Can be neutralized.',
    description: 'An ominous artifact feared for it\'s ability to prevent all that is good.',
    race: 'trap',
    otherRaces: [],
    image: '/boosts/rainbow_boost.png'
  },
  chjester: {
    title: 'chjester',
    displayTitle: 'Chjester',
    points: 0,
    amount: 1,
    rarity: 'epic',
    traitTitle: 'Surprise',
    trait: 'If your hand contains a legendary (race not boost/trap/neutral), discarding this card will instead discard the legendary (chosen at random if multiple). Cannot be found if player is protected from traps.',
    description: 'A mischievous mimic spirit that was born from the greed of humanity.',
    race: 'trap',
    otherRaces: [],
    image: '/traps/chjester.png'
  },
  exposed: {
    title: 'exposed',
    displayTitle: 'Exposed',
    points: 0,
    amount: 2,
    rarity: 'amazing',
    traitTitle: 'Expose',
    trait: 'If drawn, your hand is exposed until your next turn, unless you have a card that blocks this in some way (e.g. chastity).',
    description: 'A spirit that briefly feeds on thoughts, making them temporarily tangible and visible to the naked eye.',
    race: 'trap',
    otherRaces: [],
    image: '/traps/camo_trap.png'
  },
  sap: {
    title: 'sap',
    displayTitle: 'Sap',
    points: 0,
    amount: 2,
    rarity: 'amazing',
    traitTitle: 'Sapped',
    trait: 'When drawn player receives -10 point penalty towards all races at the end of the game even after this card is discarded.',
    description: 'A burning sticky substance that harms all who have the misfortune of touching it.',
    race: 'trap',
    otherRaces: [],
    image: '/traps/red_trap.png'
  },
  infect: {
    title: 'infect',
    displayTitle: 'Infect',
    points: 0,
    amount: 2,
    rarity: 'amazing',
    traitTitle: 'Infection',
    trait: 'When drawn player receives -1 point penalty per turn towards all races except bots and spirits (stacks) even after this card is discarded.',
    description: 'A contagious metastasizing virus that targets living hosts.',
    race: 'trap',
    otherRaces: [],
    image: '/traps/green_trap.png'
  },
  xenophobia: {
    title: 'xenophobia',
    displayTitle: 'Xenophobia',
    points: 0,
    amount: 2,
    rarity: 'great',
    traitTitle: 'Dissociate',
    trait: 'When drawn player receives -10 point penalty towards xenos at the end of the game even after this card is discarded.',
    description: 'A curious artifact that repels the xenos, harmless to others.',
    race: 'trap',
    otherRaces: [],
    image: '/traps/xeno_trap.png'
  },
  lost: {
    title: 'lost',
    displayTitle: 'Lost',
    points: 0,
    amount: 4,
    rarity: 'poor',
    traitTitle: 'Lost',
    trait: 'If drawn, lose a turn because this card is useless.',
    description: 'A harmless sprite attracted to negative energy.',
    race: 'trap',
    otherRaces: [],
    image: '/traps/white_trap.png'
  },

  // Neutrals
  neutralize: {
    title: 'neutralize',
    displayTitle: 'Neutralize',
    points: 0,
    amount: 1,
    rarity: 'legendary',
    traitTitle: 'Neutralize',
    trait: "When drawn, all boosts and traps in effect are neutralized including chastity and corruption.",
    description: 'A passive spirit that strives for balance in all things.',
    race: 'neutral',
    otherRaces: [],
    image: '/neutrals/neutralize.png'
  },
  switcharoo: {
    title: 'switcharoo',
    displayTitle: 'Switcharoo',
    points: 0,
    amount: 1,
    rarity: 'epic',
    traitTitle: 'Swap Swap',
    trait: "When discarded, players will swap hands unless player has over 6 cards or gobbledegook declared. For special xeno cards(e.g. Void Runner) they will receive the new player's point value for that card, not the previous value.",
    description: 'A trickster spirit who enjoys swapping the location of precious items.',
    race: 'neutral',
    otherRaces: [],
    image: '/neutrals/switcharoo.png'
  },
  vision: {
    title: 'vision',
    displayTitle: 'Vision',
    points: 0,
    amount: 2,
    rarity: 'amazing',
    traitTitle: 'Envision',
    trait: "When drawn you can see the opponents cards for the duration of your turn. Certain cards may block this.",
    description: 'An all seeing but passive spirit that shares its visions with others.',
    race: 'neutral',
    otherRaces: [],
    image: '/neutrals/vision.png'
  },
  echo: {
    title: 'echo',
    displayTitle: 'Echo',
    points: 0,
    amount: 3,
    rarity: 'amazing',
    traitTitle: 'Echo Echo',
    trait: "When drawn player can draw another card. Hand cannot exceed 7 cards. While hand has 7 cards, discarding an echo let's you draw another card. Turn ends when you have 5 cards in hand.",
    description: 'A self-multiplying rapidly decaying relic believed to have a soul, it appears randomly.',
    race: 'neutral',
    otherRaces: [],
    image: '/neutrals/echo.png'
  },
  leon: {
    title: 'leon',
    displayTitle: 'Leon',
    points: 0,
    amount: 2,
    rarity: 'amazing',
    traitTitle: 'Camouflage',
    trait: "Leon can blend into any race.",
    description: 'A docile chameleon who hates being mistaken for a gecko.',
    race: 'neutral',
    otherRaces: ['human', 'goblin', 'elf', 'dwarf', 'beast', 'bot', 'xeno', 'spirit'],
    image: '/neutrals/leon.png'
  },
  xenoBloom: {
    title: 'xenoBloom',
    displayTitle: 'Xeno Bloom',
    points: 0,
    amount: 1,
    rarity: 'great',
    traitTitle: 'Bloom',
    trait: "When drawn both players receive +15 xeno points at the end of the game.",
    description: 'A spirit that blesses xenos, it is believed to have been born from the countless deaths of xenos on earth.',
    race: 'neutral',
    otherRaces: [],
    image: '/neutrals/xeno_bloom.png'
  },
  ticktock: {
    title: 'ticktock',
    displayTitle: 'Ticktock',
    points: 0,
    amount: 2,
    rarity: 'great',
    traitTitle: 'Chrono Charge',
    trait: "When drawn +3 to turn count.",
    description: 'A curious sprite that briefly accelerates time when it manifests.',
    race: 'neutral',
    otherRaces: [],
    image: '/neutrals/ticktock.png'
  },
  tocktick: {
    title: 'tocktick',
    displayTitle: 'Tocktick',
    points: 0,
    amount: 1,
    rarity: 'great',
    traitTitle: 'Chrono Recharge',
    trait: "When drawn -5 to turn count (can't pass 0).",
    description: 'A curious sprite that briefly reverts time when it manifests.',
    race: 'neutral',
    otherRaces: [],
    image: '/neutrals/tocktick.png'
  },
    dwarvenCall: {
    title: 'dwarvenCall',
    displayTitle: 'Dwarven Call',
    points: 0,
    amount: 3,
    rarity: 'poor',
    traitTitle: 'Last Call',
    trait: 'When drawn the next card you draw will be a dwarf. If no dwarves are left, draw a random card.',
    description: 'It\'s really just a mug of ale, but guaranteed to summon a dwarf if one is nearby.',
    race: 'neutral',
    otherRaces: [],
    image: '/neutrals/ale.png'
  },
  xenoBlossom: {
    title: 'xenoBlossom',
    displayTitle: 'Xeno Blossom',
    points: 0,
    amount: 1,
    rarity: 'poor',
    traitTitle: 'Blossom',
    trait: "When drawn both players receive +5 xeno points at the end of the game.",
    description: 'A hatchling spirit that blesses xenos, it is believed to have been born from the countless deaths of xenos on earth.',
    race: 'neutral',
    otherRaces: [],
    image: '/neutrals/xeno_blossom.png'
  },
});

export default cardDetails;