import { writable } from 'svelte/store';
import type { Player } from './'

export const player2 = writable<Player>({
  id: undefined,
  title: 'Player 2',
  points: {
    humans: 0,
    goblins: 0,
    elves: 0,
    dwarves: 0,
    beasts: 0,
    bots: 0,
    xenos: 0,
    spirits: 0
  },
  highestPoints: 0,
  wins: 0,
  losses: 0,
  draws: 0,
  playedFirst: false,
  playingTwice: false,
  turn: false,
  giraffeCounter: 0,
  dwarfNextTurn: false,
  drewWarchief: false,
  goblinLordMarked: false,
  hand: [],
  startingHand: [],
  cardsDrawn: [],
  discards: [],
  boosts: [],
  traps: [],
  neutrals: [],
  neutralizedCards: [],
  hasChastity: false,
  hasCorruption: false,
  hasVision: false,
  isExposed: false,
  numOfCharges: 0,
  numOfGrowths: 0,
  numOfInfects: 0,
  chargePoints: 0,
  growthPoints: 0,
  infectPoints: 0,
});

export const player2Reset = writable<Player>({
  id: undefined,
  title: 'Player 2',
  points: {
    humans: 0,
    goblins: 0,
    elves: 0,
    dwarves: 0,
    beasts: 0,
    bots: 0,
    xenos: 0,
    spirits: 0
  },
  highestPoints: 0,
  wins: 0,
  losses: 0,
  draws: 0,
  playedFirst: false,
  playingTwice: false,
  turn: false,
  giraffeCounter: 0,
  dwarfNextTurn: false,
  drewWarchief: false,
  goblinLordMarked: false,
  hand: [],
  startingHand: [],
  cardsDrawn: [],
  discards: [],
  boosts: [],
  traps: [],
  neutrals: [],
  neutralizedCards: [],
  hasChastity: false,
  hasCorruption: false,
  hasVision: false,
  isExposed: false,
  numOfCharges: 0,
  numOfGrowths: 0,
  numOfInfects: 0,
  chargePoints: 0,
  growthPoints: 0,
  infectPoints: 0,
});